version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root # この変数はオプションで、イメージの起動時に作成するデータベースの名前を指定します。もしユーザ名とパスワードが指定された場合はユーザはこのデータベースへのスーパーユーザアクセス権（GRANT ALLに相当）を与えられます。
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d # Mysql8.0 ではデフォルトの認証形式を mysql_native_password から caching_sha2_password に変更している。これは回避の手段。
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/stock
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root # MYSQL_ROOT_PASSWORDに対応
      - DB_HOST=db
